### PR TITLE
Platform specific properties in manifest and copy assets folder

### PR DESCRIPTION
**Pull request by zicsus**
What does this PR do?

1. Add platform specific properties to manifest. Now you can use `chrome` and `firefox` to define browser specific properties in manifest. Please note that `chrome` is used as default configuration. 
2. Copies whole assets folder to build dir except locales as they are processed separately. 

Where to start reviewing?
gulpfile.js

Related Issues?
n/a

Caveats?
Builds file in same folder irrespective of build config. This can be an issue for parallel testing in Firefox and Chrome.

Reviewers?
@nkrusch

### CODE REVIEW

**Comment by nkrusch** [comment]
@zicsus I have merged this but I have a concern about changing the assets output directory name because it will break any existing project that assumes a different directory name. Thoughts of how to address:

- make major version increment or 
- make the directory name configurable
- or can do both actually

**Comment by zicsus** [comment]
What do you mean different directory name? 
Only thing that assets compiled was imgs, right?

**Comment by nkrusch** [comment]
Yes it compiles images only, but currently it does

```
assets/{images} -> dist/icons
```

after this change it will be

```
assets/{images} -> dist/assets
```

**Comment by zicsus** [comment]
Major version increment is better step IMO because configuration will still break existing project. With major release we can lay down all the changes.

**Pull request merged**
