### PR TITLE
Customizable webpack mode

### PR DESCRIPTION
**Pull request by nkrusch**
Enables overriding webpack mode in project by explicitly specifying it in the project build config.

### CODE REVIEW

**Comment by zicsus** [comment]
Hey, is this per script?
I think we should make it universal.

**Comment by nkrusch** [comment]
Got it, I will change it to universal.

**Comment by zicsus** [comment]
NO DON'T, Ignore the comment. We have flag for universal. I'm stupid 😅

**Comment by nkrusch** [comment]
Got it OK, no problem

**Comment by zicsus** [comment]
Can you make a release for it?

**Comment by nkrusch** [comment]
I just published 1.0.3-alpha.2

**Comment by nkrusch** [comment]
I need to update docs to include this option, but in the meantime where you have the slow build, for that script add explicit option `"mode":"development"`.

**Pull request merged**
